# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: bpbonker.npurun
PackageVersion: 0.1.0-rc.3
MinimumOSVersion: 10.0.22621.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: npurun.exe
  PortableCommandAlias: npurun
Commands:
- npurun
ReleaseDate: 2026-05-01
Installers:
- Architecture: arm64
  InstallerUrl: https://github.com/bpbonker/npurun/releases/download/v0.1.0-rc.3/npurun-0.1.0-rc.3-aarch64-windows.zip
  InstallerSha256: 9E74CD5C3272AA0753CC7B984E9B9B09AAD30630EE53681CD3D6B4860875A81D
ManifestType: installer
ManifestVersion: 1.6.0
